version: '3.8'

services:
  python-app:
    build: .
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=2003
      - DB_NAME=gold_db
    command: python 1_createDB.py

  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2003
      MYSQL_DATABASE: gold_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
